#  设置服务名
spring:
  application:
    name: service-feign
server:
  port: 8090
#  设置注册中心地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:3333/eureka
#  设置Hystrix的断路器功能
feign:
  hystrix:
    enabled: true